### ISSUE TITLE
EDA для картинок и разметок

### ISSUE THREAD

**Issue by PnthrLeo** [DreamTeamInc/Core-DS#1]
- [x] Понимание общей структуры датасета:
  - [x] Выявить общую структуру данных
  - [x] Выявить взаимосвязь между полями
  - [x] Выявить распределение кейсов (разрушенность, свечение, порода)по датасету
  - [x] Узнать Распределение фотографий по их размеру в датасете
  - [x] Распарсить .json файлы в датасет и проверить на взаимосвязь с существующими полями
- [x] Выявление отличительных особенностей классифицируемых объектов
  - [x] Выявить корреляцию между породами и наличием свечения/разломов
  - [x] На основе дескрипторов выявить отличительные характеристики каждого из классифицируемых объектов
- [x] Поиск возможных дескрипторов для изображений
  - [x] Выявить список дескрипторов, используемых на практике
  - [x] Провести первичный анализ, понять какие дескрипторы могут подойти для дальнейшего использования
- [x] Поиск метрик для задачи сегментации изображений
  - [x] Выявить существующие метрики для сегментации изображений
  - [x] Провести первичный анализ, понять какие метрики мы можем использовать в нашем проекте, можем ли мы модифицировать существующие метрики под данную задачу

**Comment by PnthrLeo** [comment]
Смотрю распределение размера фотографий

**Comment by AndyS1mpson** [comment]
Рассматриваю корреляцию признаков на фотографиях

**Comment by PnthrLeo** [comment]
Смотрю распределение кейсов по типам сегментов

**Comment by PnthrLeo** [comment]
Добавлены страницы на Core-DS/wiki с описанием EDA и найденных дескрипторов соответсвенно:
1. [EDA](https://github.com/DreamTeamInc/Core-DS/wiki/EDA)
2. [Descriptors](https://github.com/DreamTeamInc/Core-DS/wiki/Descriptors)

**Comment by PnthrLeo** [comment]
Добавлена страница на Core-DS/wiki с описанием найденных Метрик сегментации:
3. [Segmentation metrics](https://github.com/DreamTeamInc/Core-DS/wiki/Segmentation-metrics)
